# Generated by Django 5.1.4 on 2024-12-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiVasiliy', '0005_alter_rating_movie_alter_rating_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_name_de',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_de',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_de',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_de',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name_de',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='Название фильма'),
        ),
    ]
