# Generated by Django 5.1.4 on 2024-12-14 10:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiVasiliy', '0006_actor_actor_name_de_country_country_name_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('144', '144'), ('360', '360'), ('480', '480'), ('720', '720'), ('1080', '1080')], default='720', max_length=16),
        ),
    ]
