# Generated by Django 5.1.4 on 2024-12-16 08:24

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiVasiliy', '0007_alter_movie_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='actor_films', to='HiVasiliy.actor'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(to='HiVasiliy.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='HiVasiliy.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(upload_to='movie_images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name_de',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_time',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.FileField(upload_to='movie_trailer/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('144p', '144p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=16),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(to='HiVasiliy.country'),
        ),
    ]
